### ISSUE TITLE
Name and description displays twice

### ISSUE THREAD

**Issue by michalwz** [open-lms-open-source/moodle-mod_lightboxgallery#101]
Hey,
We are using moodle 4.1+
On view mood - name and description displays twice,
On editting mood - only name displays twice.

![lightbox gallery name and description displays twice](https://user-images.githubusercontent.com/46929849/234765853-ec736d9f-b8f0-4385-ad64-eb332644f191.png)
![lightbox gallery name and description displays twice - edit mood](https://user-images.githubusercontent.com/46929849/234765864-8d39b10b-b476-4f2e-839c-f0114d70fd12.png)

**Comment by aolley** [comment]
Fixed in latest, thanks!
