### ISSUE TITLE
SVG filetype not working - change accepted_types?

### ISSUE THREAD

**Issue by abomatter** [open-lms-open-source/moodle-mod_lightboxgallery#105]
Hi and thx for maintaining this plugin!  

I tried version v4.0.4, with Moodle 4.2.1 and PHP 8.1, but while .svg shows up as an "Accepted file type", it does not work and the lightboxgallery instance can't be edited anymore once I tried to upload a svg. 

![2023-08-21_13-28_filetypes](https://github.com/open-lms-open-source/moodle-mod_lightboxgallery/assets/142799097/36468257-eece-4d87-9371-38c93221e42b)

![2023-08-21_13-32_error](https://github.com/open-lms-open-source/moodle-mod_lightboxgallery/assets/142799097/95ff256a-e7bc-4c65-85da-1299f6e435e4)

It seems to me svg is not supported (by this plugin) right now, but it's still possible to upload svg-files.

I am not a programmer, but as far as I can tell the plugin uses the moodle **mimetype group "web_image"** which includes svg. 
It seems to me switching the accepted_types in the plugin-code from "web_image" to "**optimised_image**" could be an easy solution? 

The mimetype group "optimised_image" includes gif, jpeg, png, but not svg, so there will be an error message when trying to upload an svg. ("Image (SVG+XML) filetype cannot be accepted.")

![2023-08-21_13-50_optimised_image](https://github.com/open-lms-open-source/moodle-mod_lightboxgallery/assets/142799097/cb444307-2082-40ba-a4ae-353fcea000c8)

**Comment by aolley** [comment]
SVG is now accepted as of v4.0.5
