### ISSUE TITLE
Course full name fix applied to 310 branch

### ISSUE THREAD

**Issue by mnods** [open-lms-open-source/moodle-mod_lightboxgallery#94]
Hi, any chance we could get the fix
753e1910c22c6b0e048b23456178d838b13d021c
applied to the 310 branch please? - we're still on 39 so would be useful. 

cheers

**Comment by aolley** [comment]
Late reply I know - sorry. I don't intend to backport anything non-security related to anything before 3.11 (in line with upstreams version support basically).
