### ISSUE TITLE
Failing Behat test in Moodle 4.0

### ISSUE THREAD

**Issue by dragos5436** [open-lms-open-source/moodle-mod_lightboxgallery#95]
Hi,

There is one Behat test failing for this plugin:

   /var/www/html/mod/lightboxgallery/tests/behat/public_gallery.feature:7
   Feature: Set a lightboxgallery as public
   Scenario: Add a lightboxgallery and a standard gallery
```
And I follow "Edit settings": Link matching locator "Edit settings" not found. (Behat\Mink\Exception\ElementNotFoundException)
```

MySQL 5.7
PHP 7.4
Moodle latest MOODLE_400_STABLE
executed with moodlehq/moodle-docker

**Comment by aolley** [comment]
Fixed in 956523ec8cad615d08af0be9db1a0e963c1ae136
